### ISSUE TITLE
Plugin for XS 7.1 or 7.0

### ISSUE THREAD

**Issue by olivierlambert** [xenserver/xscontainer#43]
Hi guys,

I'm trying to keep up to date my blog post on using Docker+XS. Can you clarify if the pack is already included in 7.0/7.1 or not? If not where I could find it?

Thanks!

**Comment by thomasmck** [comment]
Hi Olivier,

XenServer related downloads can be found here: https://www.citrix.com/downloads/xenserver/product-software/

For the xscontainer download, navigate to the particular XS version you are interested in and look for the 'Container Management Supplemental Pack' under 'Optional components'. It is not included in box.

Kind regards,
Tom

**Comment by olivierlambert** [comment]
Thanks, I'll update the blog post :)
